# Copyright 2019,2020 Cumulus Networks, Inc.  All rights reserved.
#
#  SPDX-License-Identifier:     MIT

# Define any LABEL values that DUE can use when running the image
# These are put into the Dockerfile before creation

# If given a host build directory, mount the directory above it
# in the container as build-config needs to reference ../build

LABEL DUEMountHostDirsUp=1

# Role of container
LABEL DUEImageType=onie-build

# Version of container, for future compatibility
LABEL DUEContainerVersion=1

# Host directories to mount, if available
# This will mount a host system cache of packages.
LABEL DUEMountHostDirectories=/var/cache/onie,/dev


