# Copyright 2022 Nvidia Corporation.  All rights reserved.
#
#  SPDX-License-Identifier:     MIT

# Define any LABEL values that DUE can use when running the image
# These are put into the Dockerfile before creation

# If needed, mount the directory above the one provided.
# LABEL DUEMountHostDirsUp=1

# Container role
LABEL DUEImageType=sles-package

# Version of container, for future compatibility
LABEL DUEContainerVersion=1
