# Copyright 2022 Nvidia Corporation.  All rights reserved.
#
#  SPDX-License-Identifier:     MIT

# Define any LABEL values that DUE can use when running the image
# These are put into the Dockerfile before creation

# RPMs build in a set directory path, so do not mount one directory above.
# LABEL DUEMountHostDirsUp=1

# Container role
LABEL DUEImageType=fedora-package

# Version of container, for future compatibility
LABEL DUEContainerVersion=1