# Copyright 2022 Nvidia Corporation.  All rights reserved.
#
#  SPDX-License-Identifier:     MIT

# Define any LABEL values that DUE can use when running the image
# These are put into the Dockerfile before creation

# RPM builds have fixed paths, so no need to mount one directory up.
# LABEL DUEMountHostDirsUp=1

# Container role
LABEL DUEImageType=rhel-package

# Version of container, for future compatibility
LABEL DUEContainerVersion=1